name: support_app
description: AI Voice Customer Support
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  livekit_client: ^2.3.0
  http: ^1.1.0
  permission_handler: ^11.0.0
  url_launcher: ^6.3.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Black Han Sans
      fonts:
        - asset: assets/fonts/BlackHanSans-Regular.ttf
    - family: Jua
      fonts:
        - asset: assets/fonts/Jua-Regular.ttf
    - family: Gaegu
      fonts:
        - asset: assets/fonts/Gaegu-Bold.ttf
          weight: 700
